### ISSUE TITLE
[Feature] Have option --pool <name> and pools.json

### ISSUE THREAD

**Issue by gcarreno** [leviable/noso-go#19]
Hey Levi(@leviable),

My idea is rather simple:
1. Host a `pools.json` on this repository with the latest pools
2. Add option `--pool <name>` to the miner
3. When the `--pool <name>` option is used, read address, port and password from `pools.json` and ignore the other options apart from `--wallet` and `--cpu`

What do you think?

Cheers,
Gus

**Comment by leviable** [comment]
How would you feel about the CLI being:
`./noso-go mine pool <pool-name>` ?

so
`./noso-go mine pool yzpool`

and
`./noso-go mine pool --list` could list available options.

**Comment by gcarreno** [comment]
Hey Levi,

Ultimately it's your call, but in my view `mine`, `benchmark`, etc are commands and `--pool` is an option.
I haven't said anything but it's irking me to no end that `version` is a command and not an option :stuck_out_tongue_closed_eyes: 

So I'm more in favour of:
`nosos-go mine --pool yzpool`
and
`noso-go mine --list`
or, to lessen the ambiguity:
`noso-go mine --list-pools`

But like I said, ultimately it's your choice.

Cheers,
Gus

**Comment by leviable** [comment]
> I haven't said anything but it's irking me to no end that version is a command and not an option 😝

Yeah, lol, this is where POSIX compliance meets Go conventions. I added in support for both `noso-go --version` and `noso-go version`.
