### ISSUE TITLE
Cross compile i386 is failing

### ISSUE THREAD

**Issue by gcarreno** [leviable/noso-go#50]
Hey Levi(@leviable),

OS= Ubuntu 21.04 64b
```console
$ go version
go version go1.16.2 linux/amd64
```
Error:
```console
$ make noso-go-linux-386
# #########################################################
#
# Building noso-go binary for OS linux and Arch 386
#
# #########################################################
GOOS=linux GOARCH=386 go build -o bin/noso-go-linux-386 -ldflags "-X 'github.com/leviable/noso-go/internal/miner.Version=v1.2.0'" main.go
go tool compile: exit status 1
unsupported setting GO386=387. Consider using GO386=softfloat instead.
make: *** [Makefile:28: noso-go-linux-386] Error 1
```
I'm showing i386 only because that's the first to fail.
I'm not sure if the others will cross-compile.

Cheers,
Gus

**Comment by leviable** [comment]
Hey @gcarreno , I can't duplicate this locally:

![image](https://user-images.githubusercontent.com/11619428/118396740-7f86ab80-b616-11eb-8e47-0b572cea29ce.png)

Would you mind running the other 386 build and tell me if that works?

`make noso-go-windows-386 `

**Comment by gcarreno** [comment]
Hey Levi(@leviable),

Sure no probs:
```console
$ make noso-go-windows-386
# #########################################################
#
# Building noso-go binary for OS windows and Arch 386
#
# #########################################################
GOOS=windows GOARCH=386 go build -o bin/noso-go-windows-386 -ldflags "-X 'github.com/leviable/noso-go/internal/miner.Version=v1.2.0'" main.go
go tool compile: exit status 1
unsupported setting GO386=387. Consider using GO386=softfloat instead.
make: *** [Makefile:28: noso-go-windows-386] Error 1
```

Yeap, has the same issue.

BTW, this is happening right after upgrading from 20.10 to 21.04 and, to be honest, I can't remember what was Go's previous version under 20.10.
So it could be related to some glitch in the packaging.
Could you guide me through some sanity checks?

Cheers,
Gus

**Comment by leviable** [comment]
The Ubuntu update makes me suspect the Go install. Can you trying uninstalling Go with apt, then reinstalling?

**Comment by gcarreno** [comment]
Hey Levi(@leviable),

Yeap, I'll give it a go... errmm no pun intended!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey levi(@leviable),

```console
$ uname -a # Ubuntu 21.04 64b
Linux BatchDesk 5.11.0-17-generic #18-Ubuntu SMP Thu May 6 20:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```console
$ go version
go version go1.16.2 linux/amd64
```
Did a full remove and a full re-install(No purge) but:
```console
$ make noso-go-linux-386
# #########################################################
#
# Building noso-go binary for OS linux and Arch 386
#
# #########################################################
GOOS=linux GOARCH=386 go build -o bin/noso-go-linux-386 -ldflags "-X 'github.com/leviable/noso-go/internal/miner.Version=v1.2.0'" main.go
go tool compile: exit status 1
unsupported setting GO386=387. Consider using GO386=softfloat instead.
make: *** [Makefile:28: noso-go-linux-386] Error 1
```

Still same issue, sorry Levi :(

From the error can I deduce that it's the numerical processing unit emulation that is triggering the error?
Where can I change the config to reflect that variable `GO386`?
Maybe that's left from a previous run, but on my local folders?

Cheers,
Gus

**Comment by leviable** [comment]
@gcarreno this isn't a fix, but could you tell me if this works?

```
export GO386=softfloat
make noso-go-linux-386
```

**Comment by gcarreno** [comment]
Hey Levi(@leviable),

No need for and export since you can just put it on the command line, so this has solved it:
```console
$ GO386=softfloat make noso-go-linux-386
# #########################################################
#
# Building noso-go binary for OS linux and Arch 386
#
# #########################################################
GOOS=linux GOARCH=386 go build -o bin/noso-go-linux-386 -ldflags "-X 'github.com/leviable/noso-go/internal/miner.Version=v1.2.0'" main.go
```
And the same for the windows cross-compile:
```console
$ GO386=softfloat make noso-go-windows-386
# #########################################################
#
# Building noso-go binary for OS windows and Arch 386
#
# #########################################################
GOOS=windows GOARCH=386 go build -o bin/noso-go-windows-386 -ldflags "-X 'github.com/leviable/noso-go/internal/miner.Version=v1.2.0'" main.go
```
No errors reported.

I tested the `GO386=softfloat` with linux-amd64 and no error given but I haven't run the binary to see if it's still viable.

Cheers,
Gus

**Comment by leviable** [comment]
Alright, so the root cause here is Go changing how it compiles on 386 architectures that don't support SSE2. It's a definite edge case I don't want to try and code around in the build scripts.

For anyone in the future who might find this issue, you have two options:

* Set `GO386=softfloat` in either your ENV, or update the Makefile to set the variable
* Downgrade to a version of Go < 1.16

If you downgrade, there should be no appreciable differences in the binary

**Comment by gcarreno** [comment]
Hey Levi(@leviable),

Is there a way, cross-platform, that we can detect SSE2?

Cheers,
Gus
