### ISSUE TITLE
noso-go.sh may not be fully portable between different devices

### ISSUE THREAD

**Issue by leviable** [leviable/noso-go#53]
From the noso discord:

``` hi hi, I have a "bad interpreter" when i try to launch noso-go.sh, how could i fix it please?```

@gcarreno helped the user resolve the issue, however it did illustrated that the shell script might not be fully portable between devices.

**Comment by gcarreno** [comment]
Hey Levi(@leviable),

I'm glad you attribute the solution to me, but in the end it was something that Fury did wrong.

But I'll take the credit for the click about a more portable shebang :)

Cheers,
Gus
