### ISSUE TITLE
v1.3.X miner hanging issues

### ISSUE THREAD

**Issue by leviable** [leviable/noso-go#61]
Please comment in this issue if you experience any issues with the v1.3.X version of the miner hanging after it has been running for a while.

Please include:
What OS (Windows, Linux, MacOs)
What Arch (386, amd64, ARM, ARM64)
The log output for your miner. If you are uncomfortable including in this issue, please DM me the logs on Discord.

**Comment by daimanm** [comment]
CentOS 7 AMD64

`# ##########################################################
#
# noso-go commit-e02c8066 by levi.noecker@gmail.com (c)2021
# https://github.com/leviable/noso-go
#
# ##########################################################
Connecting to Node1.mining.moe:8082 with password miningmoe
Using wallet address: gohosted
Number of CPU cores to use: 48
-> JOIN noso-go-commit-e02c8066
<- JOINOK N3N6LZVR342iyXgZA1rGvgEfQ1SDyCW "8!!!!!!! PoolData 9774 818FF842D5643B8D796C71AE84CE69A2 11 0 104 8013860 106 337450 3
-> PAYMENT
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/leviable/noso-go/internal/miner.parseAmount(0xc0002c0069, 0x7, 0x955d40, 0xc0001574d8)
        /Users/Levi/workspace/noso-go/internal/miner/payments.go:115 +0x1c5
github.com/leviable/noso-go/internal/miner.LogPaymentReq(0x741dce, 0x10, 0x7fffd3fc27b4, 0x8, 0x262e, 0xc0002c0069, 0x7)
        /Users/Levi/workspace/noso-go/internal/miner/payments.go:24 +0x6f
github.com/leviable/noso-go/internal/miner.Mine(0x955bc0)
        /Users/Levi/workspace/noso-go/internal/miner/mine.go:162 +0x1345
github.com/leviable/noso-go/cmd.glob..func4(0x94d3a0, 0xc000070aa0, 0x1, 0x5)
        /Users/Levi/workspace/noso-go/cmd/pool.go:107 +0x11e
github.com/spf13/cobra.(*Command).execute(0x94d3a0, 0xc000070a50, 0x5, 0x5, 0x94d3a0, 0xc000070a50)
        /Users/Levi/workspace/noso-go/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x94d620, 0x41a501, 0x0, 0x0)
        /Users/Levi/workspace/noso-go/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/Levi/workspace/noso-go/vendor/github.com/spf13/cobra/command.go:897
github.com/leviable/noso-go/cmd.Execute()
        /Users/Levi/workspace/noso-go/cmd/root.go:63 +0x2d
main.main()
        /Users/Levi/workspace/noso-go/main.go:27 +0x25
`

**Comment by leviable** [comment]
@daimanm thank you, I found the bug and have that fixed on my local branch 👍
